name = "Not a UHC Pack"
author = "Luna"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eafe7f48e564ab0896a538ae3f4054ba6d2b2e4230ca536e7293ebe0c3058566"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
